### ISSUE TITLE
Fatal error: unsupported CODEC used for mzML peak data (CODEC type=zlib compression).

### ISSUE THREAD

**Issue by javanOkendo** [compomics/xtandem-parser#13]
I am getting the following error message when using X! tandem. Can someone point me to the right direction?

Command output:

  X! TANDEM Alanine (2017.2.1.4)

  Loading spectra (mzML).
  Fatal error: unsupported CODEC used for mzML peak data (CODEC type=zlib compression).

Command wrapper:

  X! TANDEM Alanine (2017.2.1.4)

  Loading spectra (mzML).
  Fatal error: unsupported CODEC used for mzML peak data (CODEC type=zlib compression).

**Comment by hbarsnes** [comment]
I'm afraid that the xtandem-parser only supports spectrum data in mgf format and not as mzML.

For questions on X! Tandem itself I have to refer you to the X! Tandem developers.

**Comment by manwarA** [comment]
Hi,
X! Tandem does not accept spectra in mgf format (or at least in KNIME supported OpenMS 2.6, Win10). The codec related issue I got in OpenMS 2.4 as well. I used different versions of X! Tandem and none of them worked. 
I used OMSSAadapter and MSGFPlus, both are working fine with the *.mzml files, but this X! Tandem refused to work. 

Any other solution is highly appreciated.

**Comment by hbarsnes** [comment]
In order to produce mzML files that are compatible with X! Tandem you have to make sure that zlib compression is turned off when converting from raw to mzML.

This can for example be done by using the ThermoRawFileParser (https://github.com/compomics/ThermoRawFileParser) and including the -z option. This will tell the converter to not use zlib compression for the m/z ratios and intensities.

**Comment by manwarA** [comment]
Any other possibility? I have only already converted MzML files and accessing the Raw data is quite difficult.

**Comment by hbarsnes** [comment]
> Any other possibility? I have only already converted MzML files and accessing the Raw data is quite difficult.

As far as I know X! Tandem does not support zlib compression at all, so if the mzML file was created with zlib compression X! Tandem will not be able to read it.

I have not tested this, or checked if it even makes any sense, but perhaps you can try converting the compressed mzML file into an uncompressed mzML file via a second conversion, for example, via msconvert (http://proteowizard.sourceforge.net)? At least msconvert is able to read the compressed values. Whether the resulting mzML file will make any sense or not I'm not sure though, so I'd very much recommend going back to the original raw files if possible.

**Comment by manwarA** [comment]
Hi, I just re-converted the mzML files with msconvert without zlib compression, and X!Tandem read the file without any error. However, it kept on working on the single fraction for 48 hours (with 1 thread and <spectrumList count="117699") and did not finish. So, I can not comment on the results whether they make any sense or not, and the file size > 1GB that notepad can't handle (I did not try with any other text editor).
Thank you for your suggestions.

**Comment by hbarsnes** [comment]
Ok, I will then close this issue as it is not really an xtandem-parser issue. For further questions about X! Tandem I'd recommend trying to contact the X! Tandem developers directly.
